@Showcase.Web.Api_HostAddress = http://localhost:7071

GET {{Showcase.Web.Api_HostAddress}}/api/products
Accept: application/json

###

GET {{Showcase.Web.Api_HostAddress}}/api/products/page?pageIndex=0&pageSize=5&sortAscending=true
Accept: application/json

###

POST {{Showcase.Web.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "demo",
  "password": "password",
  "rememberMe": false
}

###
